# Publish the Nix flake outputs to Cachix
name: Cachix
on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish Flake
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Install nix
      uses: cachix/install-nix-action@V27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Auth with Cachix
      uses: cachix/cachix-action@v15
      with:
        name: linuxing3
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

    # - name: Binary cache with Cachix
    #   uses: DeterminateSystems/magic-nix-cache-action@v2

    - name: Build nix flake
      run: nix build -L
